#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
# actions for ip-change event
#--------------------------------------------------

$event = "ip-change";

safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/ntpd");

# Configuration template expansion of ntp.conf
foreach my $file (
    qw(/etc/ntp/step-tickers /etc/ntp.conf /etc/sysconfig/clock))
{
    templates2events($file, qw(
	    timeserver-update
	    bootstrap-console-save
	));
}

#--------------------------------------------------
# actions for timeserver-update event
#--------------------------------------------------
 
$event = "timeserver-update";

safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/ntpd");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/rsyslog");

#--------------------------------------------------
# actions for timezone-update event
#--------------------------------------------------
 
$event = "timezone-update";

event_link("conf-timezone", $event, "30");
event_link("set-time-date", $event, "40");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/crond");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/rsyslog");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/squid");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/httpd");

#--------------------------------------------------
# actions for bootstrap-console-save event
#--------------------------------------------------
 
$event = "bootstrap-console-save";

event_link("conf-timezone", $event, "60");

