#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
# actions for ip-change event
#--------------------------------------------------

$event = "ip-change";

safe_symlink("condrestart", "root/etc/e-smith/events/$event/services2adjust/ntpd");

#--------------------------------------------------
# actions for time-manual-update event
#--------------------------------------------------
 
$event = "time-manual-update";

event_link("time-update", $event, "40");
templates2events("/etc/sysconfig/clock", $event);
templates2events("/etc/ntp/step-tickers", $event);
templates2events("/etc/ntp.conf", $event);
safe_symlink("stop", "root/etc/e-smith/events/$event/services2adjust/ntpd");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/crond");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/rsyslog");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/httpd");


#--------------------------------------------------
# actions for time-auto-update event
#--------------------------------------------------

$event = "time-auto-update";

event_link("time-update", $event, "40");
templates2events("/etc/sysconfig/clock", $event);
templates2events("/etc/ntp/step-tickers", $event);
templates2events("/etc/ntp.conf", $event);
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/ntpd");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/crond");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/rsyslog");
safe_symlink("restart", "root/etc/e-smith/events/$event/services2adjust/httpd");


#--------------------------------------------------
# actions for bootstrap-console-save event
#--------------------------------------------------
 
$event = "bootstrap-console-save";

event_link("time-update", $event, "60");
templates2events("/etc/ntp.conf", $event);
templates2events("/etc/ntp/step-tickers", $event);
templates2events("/etc/sysconfig/clock", $event);


#--------------------------------------------------
# actions for nethserver-ntp-update event
#--------------------------------------------------

$event = "nethserver-ntp-update";

templates2events("/etc/ntp.conf", $event);
templates2events("/etc/ntp/step-tickers", $event);
templates2events("/etc/sysconfig/clock", $event);
safe_symlink("condrestart", "root/etc/e-smith/events/$event/services2adjust/ntpd");

