#!/usr/bin/perl -w

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks qw(:all);

#--------------------------------------------------
# actions for nethserver-ntp-save event
#--------------------------------------------------
event_actions('nethserver-ntp-save', qw(
	      nethserver-ntp-localtime 40
	      nethserver-ntp-clock-adjust 41
));
	      
event_services('nethserver-ntp-save', qw(
    rsyslog condrestart
    ntpd condrestart
));

#--------------------------------------------------
# actions for nethserver-ntp-update event
#--------------------------------------------------
event_actions('nethserver-ntp-update', qw(
	      initialize-default-databases 00
	      nethserver-ntp-localtime 40
	      nethserver-ntp-clock-adjust 41
));

event_services('nethserver-ntp-update', qw(
    ntpd condrestart
));


#--------------------------------------------------
# templates
#--------------------------------------------------
event_templates($_,
		'/etc/ntp.conf',
		) foreach(qw(
  nethserver-ntp-update
  nethserver-ntp-save
));

#--------------------------------------------------
# actions for migration-import event
#--------------------------------------------------

$event = "migration-import";
event_actions($event, 'nethserver-ntp-migrate' => 50);

