#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::DB::db;
use esmith::ConfigDB;
use esmith::event;
use NethServer::Database::Timedate;
use strict;

my $event = shift;
my $sourceDir = shift;
my $esmithDbDir = '/home/e-smith/db';
my $errors = 0;
if( ! -d $sourceDir) {
    die("Could not find dir $sourceDir");
}

my $srcConfigDb = esmith::DB::db->open_ro(join('', $sourceDir, $esmithDbDir, '/configuration')) || die("Could not open source configuration database in $sourceDir \n");

my $dstConfigDb = esmith::ConfigDB->open;


my $service = 'TimeZone';
my $old = $srcConfigDb->get($service);
if( ! $old) {
    warn "[INFO] $service key not found in source ConfigDB. Nothing to do.\n";
} else {
    my $tz =  $old->prop('type') || 'UTC';
    system("/usr/bin/timedatectl set-timezone '$tz'");
}

$old = $srcConfigDb->get('ntpd');
my $new = $dstConfigDb->get('chronyd') || $dstConfigDb->new_record('chronyd');
my $server = $old->prop('NTPServer') || 'pool.ntp.org';
$new->set_prop('NTPServer', $server);

#
# Apply configuration
# 
if( ! esmith::event::event_signal('nethserver-ntp-update')) {
    exit(1);
}

exit 0;
