#!/usr/bin/perl -w

#
# NethServer Ntp
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::ConfigDB;

my $event = shift;
my $ts = shift;

my $db = esmith::ConfigDB->open or die "Could not open config db";
my $status = $db->get_prop('chronyd', 'status') || '';

if($status ne 'enabled') { 
    # manual date setting
    if( ! defined $ts) {
        warn("[NOTICE] No timestamp specified, nothing to do.");
        exit(0);
    }

    # Set the system time and hardware clock
    if(system('/bin/date', $ts) != 0) {
	die("Failed to set system time to `$ts`");
    }

    if(system('/sbin/clock', '-u', '-w') != 0) {
	die("Failed to set hardware clock to system time");
    }   
}

exit (0);
