#!/usr/bin/perl -w

#
# NethServer Ntp
#
# Copyright (C) 2012 Nethesis srl
#

use strict;
use esmith::ConfigDB;

my $event = shift || "";
my $ts = shift;

my $db = esmith::ConfigDB->open or die "Could not open config db";
my $status = $db->get_prop('ntpd', 'status') || '';

if($status eq 'enabled') { 
    qx(/sbin/service ntpd restart);
} else {
    # manual date setting
    if( ! defined $ts) {
	die("No timestamp specified");
    }

    # Set the system time and hardware clock
    if(system('/bin/date', $ts) != 0) {
	die("Failed to set system time to `$ts`");
    }

    if(system('/sbin/clock', '-u', '-w') != 0) {
	die("Failed to set hardware clock to system time");
    }   
}

exit (0);
