#!/usr/bin/perl -w

#
# NethServer Ntp
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::ConfigDB;
use File::Copy;

my $db = esmith::ConfigDB->open or die "Could not open config db";

# Obtain the TimeZone configuration database value
my $timezone = $db->get_value("TimeZone");

if ( ! defined $timezone) {
    die("Missing TimeZone value in configuration database!");
}
      
# Copy the timezone file instead of symlink, to respect CentOS behaviour
my $zoneinfo = "/usr/share/zoneinfo/" . $timezone;

if( ! -r $zoneinfo ) {
    die("Could not find zoneinfo file for time zone `$timezone`. System timezone is unchanged.");
} 

copy($zoneinfo, "/etc/localtime") or die("Failed to copy `$zoneinfo` to /etc/localtime: $!");

exit(0);
