#!/usr/bin/perl 

#
# NethServer Base
#
# Copyright (C) 2012 Nethesis srl
#

use strict;
use NethServer::Service;

my $errors = 0;

NethServer::Service::manage_add('nethserver-ntp',
				'ntp');

exit($errors == 0 ? 0 : 1);


