#!/usr/bin/perl

#
# ntp-server -- check if the given hostname has an ntp service
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;

my $host = shift || die("Missing host argument");

my $output = qx(/usr/sbin/ntpq -c 'hostnames no' -p $host 2>&1);

if($? != 0) {
    die('ntpq error ' . $!);
}

my @lines = split("\n", $output);

# save the first line in case an error occurred:
my $firstLine = @lines[0];

# the first two lines contain the header, skip them:
splice(@lines, 0, 2);

foreach(@lines) {
    # see ntpq tally codes:
    if($_ =~ m/^[o\*\+\#]/) {
	exit 0;
    }
}

print $firstLine . "\n";
exit 1;
